
import __ASTRO_IMAGE_IMPORT_Z2hJJmq from "../best-vscode-extensions-front-end-developers/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZsqLk0 from "../example-one/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-one%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z2tVl6q from "../example-three/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-three%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1jaxTN from "../example-two/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-two%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z17t0wy from "../main-author/avatar.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fauthors%2Fmain-author%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1HyAJ8 from "../tailwind-gradient-underline/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftailwind-gradient-underline%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z9jUBs from "../tsconfig-paths-setup/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftsconfig-paths-setup%2Findex.mdx";
export default new Map([["../best-vscode-extensions-front-end-developers/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z2hJJmq], ["../example-one/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-one%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZsqLk0], ["../example-three/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-three%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z2tVl6q], ["../example-two/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-two%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1jaxTN], ["../main-author/avatar.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fauthors%2Fmain-author%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z17t0wy], ["../tailwind-gradient-underline/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftailwind-gradient-underline%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1HyAJ8], ["../tsconfig-paths-setup/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftsconfig-paths-setup%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z9jUBs]]);
		