
import __ASTRO_IMAGE_IMPORT_Z2hJJmq from "../best-vscode-extensions-front-end-developers/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZPsEiB from "../best-vscode-extensions-front-end-developers/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZsqLk0 from "../example-one/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-one%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z2tVl6q from "../example-three/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-three%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1jaxTN from "../example-two/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-two%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z2aoX4r from "../exemple-deux/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fexemple-deux%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_27NxSd from "../exemple-trois/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fexemple-trois%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_11nmcV from "../exemple-un/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fexemple-un%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z17t0wy from "../main-author/avatar.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fauthors%2Fmain-author%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1HyAJ8 from "../tailwind-gradient-underline/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftailwind-gradient-underline%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1C43qi from "../tailwind-gradient-underline/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Ftailwind-gradient-underline%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z9jUBs from "../tsconfig-paths-setup/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftsconfig-paths-setup%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZGsXSV from "../tsconfig-paths-setup/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Ftsconfig-paths-setup%2Findex.mdx";
export default new Map([["../best-vscode-extensions-front-end-developers/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z2hJJmq], ["../best-vscode-extensions-front-end-developers/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZPsEiB], ["../example-one/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-one%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZsqLk0], ["../example-three/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-three%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z2tVl6q], ["../example-two/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-two%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1jaxTN], ["../exemple-deux/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fexemple-deux%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z2aoX4r], ["../exemple-trois/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fexemple-trois%2Findex.mdx", __ASTRO_IMAGE_IMPORT_27NxSd], ["../exemple-un/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Fexemple-un%2Findex.mdx", __ASTRO_IMAGE_IMPORT_11nmcV], ["../main-author/avatar.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fauthors%2Fmain-author%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z17t0wy], ["../tailwind-gradient-underline/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftailwind-gradient-underline%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1HyAJ8], ["../tailwind-gradient-underline/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Ftailwind-gradient-underline%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1C43qi], ["../tsconfig-paths-setup/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftsconfig-paths-setup%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z9jUBs], ["../tsconfig-paths-setup/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Ffr%2Ftsconfig-paths-setup%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZGsXSV]]);
		